SELECT * FROM CLIENTES_NEPTUNO;

ALTER TABLE CLIENTES_NEPTUNO
MODIFY IDCLIENTE VARCHAR(5) PRIMARY KEY,
MODIFY NOMBRECOMPANIA VARCHAR(100) NOT NULL,
MODIFY PAIS VARCHAR(15) NOT NULL;

RENAME TABLE CLIENTES TO CONTACTOS;

ALTER TABLE CLIENTES
MODIFY COD_CLIENTE VARCHAR(7) PRIMARY KEY,
MODIFY EMPRESA VARCHAR(100),
MODIFY CIUDAD VARCHAR(25),
MODIFY TELEFONO INT UNSIGNED,
MODIFY RESPONSABLE VARCHAR(30);

ALTER TABLE PEDIDOS
MODIFY NUMERO_PEDIDO INT PRIMARY KEY,
MODIFY CODIGO_CLIENTE VARCHAR(7) NOT NULL,
MODIFY FECHA_PEDIDO DATE NOT NULL,
MODIFY FORMA_PAGO ENUM ('APLAZADO', 'CONTADO','TARJETA'),
MODIFY ENVIADO ENUM ('SI', 'NO');

ALTER TABLE PRODUCTOS
MODIFY COD_PRODUCTO INT PRIMARY KEY,
MODIFY SECCION VARCHAR(20) NOT NULL,
MODIFY NOMBRE VARCHAR(40) NOT NULL,
MODIFY IMPORTADO ENUM ('VERDADERO','FALSO') NOT NULL,
MODIFY ORIGEN VARCHAR(25) NOT NULL,
MODIFY DIA INT UNSIGNED NOT NULL, 
MODIFY MES INT UNSIGNED NOT NULL, 
MODIFY ANO INT UNSIGNED NOT NULL;